version: '3.9'
volumes:
  postgres_data: {}

services:
  app-dev:
    container_name: psychology_instruments
    build:
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=password
    entrypoint: ['./entrypoint-dev.sh']
    command: ['rails', 's', '-b', '0.0.0.0']
    restart: unless-stopped
    ports:
      - "3003:3000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
  db:
    container_name: db_psychology_instruments_dev
    image: postgres:14.9-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psychology_instruments_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
